In [454]:
import pandas as pd
import numpy as np
import scipy as sp
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder,MinMaxScaler,OneHotEncoder,add_dummy_feature
import re
import collections
import cPickle as cp
#import string as str

In [120]:
rsc = pd.read_csv('/home/nishant/Downloads/Data/regular_season_compact_results.csv')
rsc[(rsc['season']==2014)&(rsc['wteam']==1228)]

        season  daynum  wteam  wscore  lteam  lscore wloc  numot
129235    2014       4   1228      80   1106      63    H      0
129355    2014       6   1228      86   1240      62    H      0
129472    2014       9   1228      64   1434      52    H      0
129637    2014      13   1228      81   1133      55    H      0
129836    2014      18   1228      77   1152      53    H      0
130049    2014      22   1228      61   1424      59    A      0
130164    2014      25   1228      57   1236      55    H      0
130571    2014      34   1228      81   1120      62    N      0
130597    2014      36   1228      72   1171      65    H      0
130912    2014      47   1228      65   1281      64    N      0
131080    2014      54   1228      74   1227      60    N      0
131212    2014      57   1228      83   1231      80    H      1
131366    2014      61   1228      75   1336      55    H      0
133082    2014      97   1228      60   1336      55    A      0
133477    2014     107   1228      62   1278      49    A      0
133800    2014     114   1228      60   1304      49    H      0
133959    2014     117   1228      53   1277      46    A      0
134285    2014     124   1228      66   1234      63    A      0
134452    2014     129   1228      64   1231      54    N      0

In [48]:
rsd=pd.read_csv('/home/nishant/Downloads/Data/regular_season_detailed_results.csv')
rsd.head()

,season,daynum,wteam,wscore,lteam,lscore,wloc,numot,wfgm,wfga,...,lfga3,lftm,lfta,lor,ldr,last,lto,lstl,lblk,lpf
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14

In [137]:
tourc=pd.read_csv('/home/nishant/Downloads/Data/tourney_compact_results.csv')
tourc.head()
champlist=tourc[tourc['daynum']==154]['wteam'].tolist()
print champlist

[1437, 1257, 1231, 1242, 1276, 1424, 1181, 1181, 1314, 1116, 1417, 1246, 1112, 1246, 1163, 1277, 1181, 1268, 1393, 1163, 1314, 1196, 1196, 1242, 1314, 1181, 1163, 1246, 1257, 1163]

In [50]:
tourd=pd.read_csv('/home/nishant/Downloads/Data/tourney_detailed_results.csv')
tourd.head()

,season,daynum,wteam,wscore,lteam,lscore,wloc,numot,wfgm,wfga,...,lfga3,lftm,lfta,lor,ldr,last,lto,lstl,lblk,lpf
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,14,31,17,28,16,15,5,0,22
1,2003,136,1112,80,1436,51,N,0,31,66,...,16,7,7,8,26,12,17,10,3,15
2,2003,136,1113,84,1272,71,N,0,31,59,...,28,14,21,20,22,11,12,2,5,18
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,12,17,14,17,20,21,6,6,21
4,2003,136,1143,76,1301,74,N,1,27,64,...,21,15,20,10,26,16,14,5,8,19

In [51]:
seed=pd.read_csv('/home/nishant/Downloads/Data/tourney_seeds.csv')
seed.head()

   season seed  team
0    1985  W01  1207
1    1985  W02  1210
2    1985  W03  1228
3    1985  W04  1260
4    1985  W05  1374

In [52]:
seed15=pd.read_csv('/home/nishant/Downloads/Data/tourney_seeds_2015.csv')
seed15.head()

   season seed  team
0    2015  W01  1437
1    2015  W02  1438
2    2015  W03  1328
3    2015  W04  1257
4    2015  W05  1320

In [53]:
slot=pd.read_csv('/home/nishant/Downloads/Data/tourney_slots.csv')
slot.head()

   season  slot strongseed weakseed
0    1985  R1W1        W01      W16
1    1985  R1W2        W02      W15
2    1985  R1W3        W03      W14
3    1985  R1W4        W04      W13
4    1985  R1W5        W05      W12

In [54]:
slot15=pd.read_csv('/home/nishant/Downloads/Data/tourney_slots_2015.csv')
slot15.head()

   season  slot strongseed weakseed
0    2015   W11       W11a     W11b
1    2015   X16       X16a     X16b
2    2015   Y16       Y16a     Y16b
3    2015   Z11       Z11a     Z11b
4    2015  R1W1        W01      W16

In [475]:
teams=pd.read_csv('/home/nishant/Downloads/Data/teams.csv')
teamlist=teams['team_id'].tolist()

teams.head()

364

   team_id    team_name
0     1101  Abilene Chr
1     1102    Air Force
2     1103        Akron
3     1104      Alabama
4     1105  Alabama A&M

In [62]:
def getTeamID(name):
    return teams[teams['team_name'] == name].values[0][0]

In [229]:
def totalwinsr(team_id,year):
    return len(rsc[(rsc['wteam']==team_id) & (rsc['season']<year)])

In [143]:
def teamname(team_id):
    return teams[teams['team_id'] == team_id].values[0][1]

In [230]:
def totalwinst(team_id,year):
    return len(tourc[(tourc['wteam']==team_id) & (tourc['season']<year)])

In [227]:
def getseed(team_id,year):
    txt=seed[(seed['season']==year)&(seed['team']==team_id)]
    if(len(txt.index)!=0):
        txt=txt.values[0][1]
        match=re.search(r'\d+',txt)
        return int(match.group())
    else: return 25

In [135]:
def totaltrophies(team_id):
    return champlist.count(team_id)

In [304]:
def form(team_id,year):
    last6r=rsc[((rsc['wteam']==team_id) | (rsc['lteam']==team_id)) & (rsc['season']<year)].tail(6)
    last6t=tourc[((tourc['wteam']==team_id) | (tourc['lteam']==team_id)) & (tourc['season']<year)].tail(6)
    rec=float(float(len(last6r[last6r['wteam']==team_id])+len(last6t[last6t['wteam']==team_id]))/12)
    return rec

In [296]:
def tourapps(team_id):
    count=0
    for year in range(1985,2014):
        count+=team_id in np.concatenate([np.asarray(tourc[tourc['season']==year]['wteam'].values),np.asarray(tourc[tourc['season']==year]['lteam'].values)])
    return count

In [458]:
def sos(team_id,year):
    dat=rsc[(rsc['season']==year)]
    def owp(tid):
        lopp=list(dat[dat.wteam==tid].lteam.values)
        wopp=list(dat[dat.lteam==tid].wteam.values)
        allopp=lopp+wopp
        wp=[]
        for i in allopp:
            won=len(dat[(dat.wteam==i)&(dat.lteam!=tid)].index)
            lost=len(dat[(dat.lteam==i)&(dat.wteam!=tid)].index)
            wp.append(float(won)/(won+lost)*100)
        if(len(wp)!=0):
            return float(sum(wp))/len(wp)
        else:
            return 0
    op=owp(team_id)
    oppl=list(dat[dat.wteam==team_id].lteam.values)
    oppw=list(dat[dat.lteam==team_id].wteam.values)
    oppall=oppl+oppw
    oop=[]
    for j in oppall:
        oop.append(owp(j))
    if(len(oop)!=0):
        oop=float(sum(oop))/len(oop)
    else:
        oop=0
    SOS=(2*op+oop)/3
    

    #lis=list(np.concatenate([np.asarray(dat['wteam']==team_id),np.asarray(dat['lteam']==team_id)]))
    #flist=list(set(teamlist).intersection(lis))
    #OOR=[]
    #oppr=[]
    #for tid in flist:
        #OR=[]
        #newlist=[x for x in flist if x!=tid]
        #for i in newlist:
           # won=len(dat[(dat.wteam==i)&(dat.lteam!=tid)].index)
           # lost=len(dat[(dat.lteam==i)&(dat.wteam!=tid)].index)
           # if won+lost!=0:
             #   OR.append(round(float(won/(won+lost)),2))
            #else:
           #     continue
        #if tid==team_id:
        #    oppr.append(sum(OR)/float(len(OR)))
        #else:
           # OOR.append(sum(OR)/float(len(OR)))
    #OOR=sum(OOR)/float(len(OOR))
    #SOS=(2*oppr[0]+OOR)/3
    return SOS

In [460]:
def seasonstat(team_id,year):
    games_won=rsc[(rsc['season']==year)&(rsc['wteam']==team_id)]
    games_lost=rsc[(rsc['season']==year)&(rsc['lteam']==team_id)]
    totalpoints = games_won['wscore'].sum()+games_lost['lscore'].sum()
    points_conceded=games_won['lscore'].sum()+games_lost['wscore'].sum()
    wins=len(games_won.index)
    seed=getseed(team_id,year)#seed in the tournament
    whr=totalwinsr(team_id,year)#total regular season wins in history
    wht=totalwinst(team_id,year)#total tournament wins in history
    rec=round(form(team_id,year),2)#overall performance in last 6 regular and tournament games
    trophies=totaltrophies(team_id)#total tournaments won by the team
    numgames=len(games_won.index)+len(games_lost.index)
    games_dwon=rsd[(rsd['season']==year)&(rsd['wteam']==team_id)]
    games_dlost=rsd[(rsd['season']==year)&(rsd['lteam']==team_id)]
    totaldgames=len(games_dwon.index)+len(games_dlost.index)
    count=0
    for year in range(1985,2014):
        count+=team_id in np.concatenate([np.asarray(tourc[tourc['season']==year]['wteam'].values),np.asarray(tourc[tourc['season']==year]['lteam'].values)])
    app=count
    strength_of_schedule=round(sos(team_id,year),2)
    if(totaldgames==0):
        fg=0
        to=0
        fg3=0
        rb=0
        stl=0
        assist=0
        tp=0
        pc=0
    else:
        fg=round(float((games_dwon['wfgm'].sum()+games_dlost['lfgm'].sum()))/totaldgames,2)#fieldgoals
        to=round(float((games_dwon['wto'].sum()+games_dlost['lto'].sum()))/totaldgames,2)#turnovers
        fg3=round(float((games_dwon['wfgm3'].sum()+games_dlost['lfgm3'].sum()))/totaldgames,2)#fieldgoals3pointers
        rb=round(float((games_dwon['wor'].sum()+games_dlost['lor'].sum()))/totaldgames,2)#rebounds
        stl=round(float((games_dwon['wstl'].sum()+games_dlost['lstl'].sum()))/totaldgames,2)#steals
        assist=round(float((games_dwon['wast'].sum()+games_dlost['last'].sum()))/totaldgames,2)#assists
        tp=round(float(totalpoints)/totaldgames,2)#totalpointsscored
        pc=round(float(points_conceded)/totaldgames,2)#totalpointsconceded
        #allaverage
    return [wins,seed,whr,wht,rec,trophies,app,fg,to,fg3,rb,stl,assist,tp,pc,strength_of_schedule]

In [450]:
seasonstat(1228,2014)

[19,
 25,
 607,
 28,
 0.33,
 0,
 22,
 22.82,
 10.48,
 6.03,
 11.03,
 6.15,
 10.12,
 64.64,
 62.55,
 58.73]

In [318]:
def diffteams(id_1, id_2, year):
    team_1 = seasonstat(id_1, year)
    team_2 = seasonstat(id_2, year)
    diff = [a - b for a, b in zip(team_1, team_2)]
    return diff

In [480]:
def location(val):
    if (val == 'H'):
        home = 1
    if (val == 'A'):
        home = -1
    if (val == 'N'):
        home = 0
    return home

In [ ]:
def h2h(team1,team2):
    pass

In [462]:
def seasondict(year):
    seadict = collections.defaultdict(list)
    for team in teamlist:
        team_vector = seasonstat(team, year)
        seadict[team] = team_vector
    return seadict

282

In [491]:
def trainingdata(years):
    totalgames = 0
    for year in years:
        season = rsc[rsc['season'] == year]
        totalgames += len(season.index)
        tourney = tourc[tourc['season'] == year]
        totalgames += len(tourney.index)
    featuresize = len(seasonstat(1181,2012)) #dimension of feature vecture
    x_train = np.zeros(( totalgames, featuresize + 1))
    y_train = np.zeros(( totalgames ))
    idx = 0
    for year in years:
        team_vect = seasondict(year)
        season = rsc[rsc['season'] == year]
        seasongames = len(season.index)
        tourney = tourc[tourc['season'] == year]
        seasongames += len(tourney.index)
        x_trainseason = np.zeros(( seasongames, featuresize + 1))
        y_trainseason = np.zeros(( seasongames ))
        count = 0
        for _, row in season.iterrows():
            w_team = row['wteam']
            w_vector = team_vect[w_team]
            l_team = row['lteam']
            l_vector = team_vect[l_team]
            diff = [a - b for a, b in zip(w_vector, l_vector)]
            loc = location(row['wloc'])
            if (count % 2 == 0):
                diff.append(loc) 
                x_trainseason[count] = diff
                y_trainseason[count] = 1
            else:
                diff.append(-loc)
                x_trainseason[count] = [ -p for p in diff]
                y_trainseason[count] = 0
            count += 1
        for _, row in tourney.iterrows():
            w_team = row['wteam']
            w_vector = team_vect[w_team]
            l_team = row['lteam']
            l_vector = team_vect[l_team]
            diff = [a - b for a, b in zip(w_vector, l_vector)]
            loc = 0 #All tournament games are neutral
            if (count % 2 == 0):
                diff.append(loc) 
                x_trainseason[count] = diff
                y_trainseason[count] = 1
            else:
                diff.append(-loc)
                x_trainseason[count] = [ -p for p in diff]
                y_trainseason[count] = 0
            count += 1
        x_train[idx:seasongames+idx] = x_trainseason
        y_train[idx:seasongames+idx] = y_trainseason
        idx += seasongames
    return x_train, y_train

In [464]:
print seasondict(2005)

defaultdict(<type 'list'>, {1101: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0], 1102: [17, 25, 144, 0, 0.33, 0, 2, 21.41, 10.07, 8.9, 7.62, 8.79, 13.66, 61.24, 55.14, 55.56], 1103: [18, 25, 252, 0, 0.17, 0, 4, 24.79, 13.36, 8.14, 10.29, 6.75, 16.11, 71.61, 66.25, 51.34], 1104: [23, 5, 390, 17, 0.58, 0, 15, 25.37, 12.67, 7.63, 10.23, 5.2, 13.83, 75.43, 64.83, 54.69], 1105: [16, 16, 66, 0, 0.25, 0, 1, 23.66, 15.24, 6.1, 12.93, 10.62, 13.14, 69.07, 67.79, 41.03], 1106: [15, 25, 229, 0, 0.5, 0, 4, 19.43, 15.77, 4.53, 11.27, 6.7, 10.37, 57.97, 61.3, 42.13], 1107: [13, 25, 33, 0, 0.08, 0, 3, 23.0, 14.79, 6.21, 11.07, 8.04, 13.07, 67.36, 64.68, 45.65], 1108: [6, 25, 213, 0, 0.25, 0, 2, 19.96, 19.86, 4.71, 11.07, 7.46, 11.04, 57.18, 69.46, 44.39], 1109: [0, 25, 42, 0, 0.08, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0], 1110: [16, 25, 222, 0, 0.42, 0, 2, 24.29, 15.0, 6.36, 10.04, 6.57, 12.89, 67.18, 66.07, 47.15], 1111: [15, 25, 249, 0, 0.08, 0, 1, 25.85, 15.0, 8.33, 12.15, 9.07, 15.56, 71.52, 69.63, 43.58], 1112: [27, 3, 466, 35, 0.5, 1, 27, 29.12, 14.85, 6.85, 13.73, 8.24, 16.58, 79.67, 69.55, 57.24], 1113: [18, 25, 282, 4, 0.33, 0, 4, 25.87, 14.68, 6.9, 12.81, 6.39, 16.45, 75.97, 71.65, 52.93], 1114: [15, 25, 315, 1, 0.42, 0, 4, 23.16, 14.96, 4.84, 10.12, 6.44, 12.32, 66.52, 67.88, 49.67], 1115: [5, 25, 15, 0, 0.0, 0, 1, 21.69, 16.81, 4.35, 11.31, 6.85, 11.42, 58.19, 68.62, 43.15], 1116: [18, 25, 396, 27, 0.25, 1, 17, 25.77, 14.23, 6.07, 12.3, 8.73, 14.5, 71.57, 62.83, 54.03], 1117: [13, 25, 284, 0, 0.25, 0, 1, 26.73, 14.81, 5.88, 13.65, 6.54, 13.92, 74.12, 73.42, 46.9], 1118: [0, 25, 6, 0, 0.08, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0], 1119: [1, 25, 146, 0, 0.08, 0, 0, 18.68, 15.4, 6.08, 6.04, 4.92, 10.88, 54.32, 69.2, 45.73], 1120: [14, 25, 309, 12, 0.33, 0, 7, 24.42, 14.48, 8.35, 11.29, 7.35, 12.97, 70.68, 75.23, 52.15], 1121: [0, 25, 48, 0, 0.42, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0], 1122: [13, 25, 265, 1, 0.42, 0, 4, 23.16, 14.28, 6.0, 10.59, 6.88, 12.91, 65.31, 67.09, 46.83], 1123: [14, 25, 339, 3, 0.5, 0, 6, 24.0, 12.26, 7.3, 12.3, 5.48, 11.56, 69.78, 68.81, 45.55], 1124: [8, 25, 243, 0, 0.08, 0, 4, 22.37, 16.0, 7.7, 10.59, 7.37, 13.07, 65.59, 72.48, 57.17], 1125: [14, 25, 60, 0, 0.33, 0, 6, 23.9, 14.47, 9.73, 9.4, 7.43, 13.8, 70.27, 70.03, 54.13], 1126: [13, 25, 160, 0, 0.25, 0, 0, 23.7, 16.33, 6.43, 9.33, 8.1, 13.57, 64.37, 68.57, 44.95], 1127: [12, 25, 37, 0, 0.25, 0, 1, 21.52, 13.59, 6.69, 12.38, 6.69, 10.41, 61.52, 63.41, 47.32], 1128: [15, 25, 35, 0, 0.33, 0, 0, 20.76, 13.38, 6.69, 9.9, 5.0, 10.62, 64.17, 63.17, 0.0], 1129: [15, 25, 312, 0, 0.42, 0, 5, 25.36, 15.12, 7.85, 12.58, 5.24, 13.64, 70.88, 74.91, 55.63], 1130: [24, 4, 300, 9, 0.58, 0, 11, 25.54, 12.93, 4.0, 14.32, 7.25, 17.39, 71.93, 63.82, 56.05], 1131: [20, 25, 322, 0, 0.42, 0, 5, 23.07, 12.0, 4.61, 11.0, 7.04, 12.5, 63.86, 55.43, 47.61], 1132: [17, 25, 274, 0, 0.17, 0, 0, 24.32, 14.86, 6.46, 8.68, 6.54, 16.57, 69.14, 68.93, 48.03], 1133: [13, 25, 311, 1, 0.42, 0, 4, 24.96, 15.93, 5.39, 12.5, 7.43, 13.54, 69.96, 71.29, 48.83], 1134: [0, 25, 50, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0], 1135: [12, 25, 191, 0, 0.33, 0, 1, 22.14, 14.32, 7.18, 9.89, 9.0, 13.36, 66.04, 67.79, 45.1], 1136: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46.31], 1137: [22, 14, 297, 0, 0.25, 0, 6, 21.26, 15.77, 6.61, 9.35, 8.0, 12.45, 63.58, 58.45, 48.44], 1138: [22, 25, 124, 0, 0.42, 0, 0, 26.77, 15.84, 6.94, 12.77, 8.77, 14.23, 75.19, 71.39, 49.93], 1139: [11, 25, 323, 3, 0.58, 0, 11, 21.81, 10.04, 8.19, 6.12, 4.62, 11.35, 63.54, 62.08, 56.58], 1140: [7, 25, 359, 3, 0.5, 0, 16, 22.11, 14.68, 7.0, 11.39, 5.75, 11.82, 63.75, 69.43, 53.74], 1141: [8, 25, 187, 1, 0.25, 0, 2, 23.04, 17.65, 6.81, 11.38, 7.31, 12.19, 66.12, 76.38, 47.58], 1142: [4, 25, 93, 0, 0.25, 0, 0, 23.12, 16.77, 7.0, 10.04, 6.27, 10.31, 67.23, 80.15, 47.69], 1143: [13, 25, 327, 7, 0.33, 0, 13, 25.45, 14.9, 3.79, 12.0, 4.86, 14.55, 67.45, 70.83, 56.31], 1144: [2, 25, 182, 0, 0.08, 0, 1, 22.93, 18.78, 4.81, 13.7, 6.48, 10.81, 62.26, 76.48, 45.0], 1145: [11, 25, 270, 0, 0.08, 0, 1, 26.24, 13.52, 6.72, 11.07, 7.38, 13.07, 72.03, 76.31, 50.26], 1146: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 44.23], 1147: [2, 25, 196, 0, 0.25, 0, 0, 21.85, 16.58, 6.62, 9.92, 6.15, 11.12, 63.23, 78.15, 0.0], 1148: [12, 25, 188, 0, 0.33, 0, 3, 24.11, 14.5, 6.64, 12.39, 6.04, 13.68, 68.54, 69.57, 48.34], 1149: [12, 25, 198, 0, 0.25, 0, 1, 21.5, 15.57, 5.21, 9.14, 7.0, 12.14, 57.89, 63.86, 44.83], 1150: [21, 7, 326, 4, 0.5, 0, 10, 26.43, 13.18, 8.0, 14.57, 8.71, 14.21, 78.36, 72.07, 53.12], 1151: [17, 15, 329, 2, 0.5, 0, 7, 24.48, 17.41, 5.26, 13.52, 7.04, 13.52, 70.44, 67.56, 45.4], 1152: [9, 25, 116, 0, 0.25, 0, 0, 23.29, 13.68, 5.39, 11.18, 8.04, 11.79, 64.57, 70.71, 45.14], 1153: [24, 7, 408, 19, 0.58, 0, 17, 25.55, 13.45, 6.61, 14.39, 5.48, 15.0, 76.42, 64.42, 57.16], 1154: [8, 25, 168, 0, 0.17, 0, 0, 22.08, 17.58, 6.67, 12.21, 7.54, 9.54, 64.38, 71.71, 43.6], 1155: [16, 25, 311, 5, 0.25, 0, 10, 26.03, 17.48, 6.1, 14.13, 9.97, 14.35, 71.61, 68.9, 52.44], 1156: [7, 25, 274, 2, 0.17, 0, 2, 22.96, 16.67, 6.83, 11.75, 7.75, 14.08, 67.0, 72.29, 50.94], 1157: [8, 25, 192, 0, 0.25, 0, 2, 24.73, 14.12, 7.12, 12.04, 7.42, 14.08, 67.92, 73.19, 45.83], 1158: [18, 25, 269, 1, 0.25, 0, 4, 25.75, 13.54, 6.32, 12.86, 8.89, 14.82, 72.07, 67.75, 46.12], 1159: [10, 25, 202, 0, 0.33, 0, 2, 23.54, 14.65, 6.69, 9.88, 5.42, 12.5, 64.5, 68.15, 47.34], 1160: [13, 25, 250, 1, 0.42, 0, 4, 25.55, 13.9, 7.34, 12.48, 6.07, 13.69, 71.21, 74.79, 57.39], 1161: [9, 25, 293, 1, 0.25, 0, 5, 23.77, 16.04, 4.85, 10.69, 5.69, 15.23, 69.23, 70.38, 56.44], 1162: [12, 25, 155, 0, 0.33, 0, 0, 21.89, 17.56, 7.3, 11.04, 6.59, 13.67, 64.22, 65.67, 45.34], 1163: [22, 2, 409, 34, 0.92, 4, 18, 27.97, 15.21, 5.14, 15.69, 6.17, 17.41, 78.62, 66.76, 56.94], 1164: [14, 25, 296, 1, 0.42, 0, 4, 20.76, 14.79, 3.55, 11.93, 8.52, 9.59, 60.86, 63.21, 45.96], 1165: [12, 25, 197, 0, 0.08, 0, 4, 22.65, 14.19, 6.92, 9.15, 6.81, 12.92, 64.0, 66.19, 45.97], 1166: [23, 10, 320, 3, 0.25, 0, 11, 24.3, 11.97, 8.64, 9.88, 6.85, 14.27, 71.52, 64.97, 54.42], 1167: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 47.12], 1168: [18, 25, 211, 0, 0.17, 0, 1, 28.43, 13.36, 7.89, 12.96, 6.75, 14.86, 74.07, 71.07, 44.44], 1169: [17, 25, 155, 0, 0.25, 0, 2, 24.9, 16.2, 5.57, 11.93, 10.87, 13.8, 71.67, 67.5, 46.08], 1170: [10, 25, 61, 0, 0.25, 0, 0, 22.69, 14.96, 6.85, 14.88, 9.65, 11.31, 68.27, 74.31, 42.47], 1171: [9, 25, 204, 0, 0.0, 0, 0, 20.88, 14.15, 6.08, 9.08, 6.62, 12.58, 57.54, 64.77, 46.39], 1172: [18, 25, 255, 0, 0.42, 0, 8, 23.65, 15.35, 8.5, 12.38, 5.04, 13.88, 70.58, 67.96, 48.49], 1173: [18, 25, 304, 1, 0.42, 0, 6, 22.03, 13.1, 7.72, 11.48, 5.86, 13.34, 64.72, 61.59, 53.7], 1174: [11, 25, 305, 0, 0.17, 0, 4, 23.32, 16.71, 5.87, 10.87, 6.16, 12.9, 65.06, 68.26, 48.98], 1175: [19, 16, 194, 0, 0.33, 0, 1, 20.25, 14.06, 6.5, 10.16, 8.16, 10.66, 62.41, 61.84, 43.3], 1176: [18, 25, 60, 0, 0.08, 0, 0, 26.29, 13.36, 6.0, 10.25, 7.25, 15.36, 72.75, 67.0, 50.71], 1177: [19, 25, 320, 7, 0.5, 0, 9, 24.76, 12.28, 5.72, 13.41, 5.69, 14.03, 68.03, 63.48, 53.09], 1178: [13, 25, 281, 2, 0.58, 0, 3, 22.62, 13.07, 4.14, 13.21, 5.9, 10.79, 61.31, 60.69, 53.38], 1179: [13, 25, 206, 0, 0.17, 0, 1, 22.66, 15.69, 5.93, 13.24, 8.21, 12.07, 69.31, 71.62, 54.22], 1180: [17, 25, 335, 1, 0.33, 0, 4, 23.25, 12.0, 7.71, 10.29, 6.21, 14.21, 69.5, 65.46, 48.86], 1181: [25, 1, 496, 64, 0.67, 4, 28, 26.53, 13.6, 8.97, 13.5, 8.77, 13.2, 79.77, 65.8, 60.68], 1182: [8, 25, 206, 0, 0.25, 0, 0, 24.6, 13.87, 5.93, 12.37, 6.33, 14.67, 67.13, 74.63, 53.93], 1183: [11, 25, 248, 0, 0.17, 0, 2, 23.59, 15.56, 6.0, 10.85, 4.85, 13.63, 67.7, 72.37, 46.34], 1184: [19, 15, 189, 0, 0.25, 0, 2, 26.26, 14.22, 6.19, 10.93, 6.85, 14.67, 70.37, 67.48, 49.41], 1185: [10, 25, 260, 3, 0.5, 0, 4, 23.79, 15.21, 5.68, 10.82, 7.29, 12.21, 72.46, 75.61, 47.7], 1186: [7, 25, 186, 0, 0.33, 0, 1, 21.78, 16.26, 6.19, 9.37, 5.19, 13.67, 61.41, 67.67, 43.59], 1187: [7, 25, 218, 0, 0.33, 0, 1, 22.12, 16.08, 4.27, 14.35, 5.96, 11.73, 62.62, 70.92, 53.76], 1188: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46.86], 1189: [7, 25, 47, 0, 0.25, 0, 0, 21.24, 15.48, 5.62, 9.79, 7.69, 10.76, 59.97, 68.1, 44.35], 1190: [7, 25, 277, 1, 0.5, 0, 8, 27.46, 16.77, 6.65, 12.27, 7.77, 11.08, 74.58, 81.08, 48.11], 1191: [11, 25, 312, 1, 0.25, 0, 4, 24.82, 14.11, 8.18, 9.57, 4.75, 15.64, 70.93, 73.04, 53.17], 1192: [19, 16, 300, 0, 0.25, 0, 4, 27.06, 13.9, 6.68, 12.45, 7.13, 15.03, 74.16, 70.9, 47.2], 1193: [15, 25, 253, 0, 0.33, 0, 3, 24.53, 13.07, 5.3, 12.3, 7.53, 14.6, 68.03, 67.0, 46.8], 1194: [10, 25, 81, 0, 0.08, 0, 1, 27.67, 17.26, 7.15, 14.3, 8.7, 13.19, 76.78, 78.67, 48.09], 1195: [0, 25, 0, 0, 0.0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 47.84], 1196: [23, 4, 358, 16, 0.5, 2, 18, 26.77, 13.63, 7.67, 11.5, 7.03, 15.03, 76.87, 62.73, 57.58], 1197: [14, 25, 211, 1, 0.42, 0, 3, 24.21, 17.28, 5.38, 13.69, 7.34, 11.31, 68.0, 73.83, 43.87], 1198: [12, 25, 176, 0, 0.08, 0, 1, 23.14, 18.83, 4.59, 12.69, 6.86, 13.03, 67.14, 71.38, 50.7], 1199: [11, 25, 297, 7, 0.42, 0, 10, 24.03, 16.13, 6.47, 9.93, 6.77, 12.37, 68.0, 70.17, 56.33], 1200: [13, 25, 238, 0, 0.17, 0, 1, 22.34, 16.38, 6.52, 12.14, 7.52, 13.17, 63.07, 64.52, 54.46], 1201: [15, 25, 319, 1, 0.25, 0, 2, 25.48, 15.9, 7.38, 12.28, 5.66, 14.93, 71.72, 70.9, 57.87], 1202: [12, 25, 213, 0, 0.33, 0, 0, 24.04, 15.12, 8.4, 10.4, 8.24, 14.8, 67.72, 67.96, 42.94], 1203: [22, 12, 296, 3, 0.33, 0, 8, 27.72, 14.97, 5.38, 13.03, 9.79, 16.03, 77.24, 66.93, 54.19], 1204: [14, 25, 270, 0, 0.25, 0, 2, 27.89, 15.63, 6.56, 13.7, 9.78, 14.59, 79.59, 76.59, 45.11], 1205: [16, 25, 11, 0, 0.25, 0, 0, 25.39, 15.36, 7.39, 13.11, 7.86, 14.07, 71.25, 69.04, 43.03], 1206: [16, 25, 285, 0, 0.42, 0, 6, 25.38, 12.38, 6.97, 11.34, 7.93, 14.41, 73.34, 69.59, 49.21], 1207: [17, 25, 359, 24, 0.25, 0, 20, 22.66, 13.9, 7.52, 10.59, 6.9, 14.0, 64.03, 61.9, 57.95], 1208: [8, 25, 336, 4, 0.42, 0, 10, 20.89, 15.25, 5.46, 11.14, 7.46, 9.68, 60.11, 67.79, 55.06], 1209: [13, 25, 233, 1, 0.5, 0, 2, 24.64, 13.07, 8.71, 11.18, 6.32, 12.86, 70.04, 72.46, 47.35], 1210: [19, 5, 364, 20, 0.75, 0, 15, 26.7, 15.3, 5.9, 12.77, 8.27, 14.97, 74.57, 66.3, 52.59], 1211: [25, 3, 352, 9, 0.67, 0, 16, 27.59, 13.55, 5.03, 11.72, 5.59, 15.83, 79.69, 69.79, 54.72], 1212: [12, 25, 166, 0, 0.25, 0, 0, 24.13, 15.42, 6.63, 11.79, 6.5, 14.21, 66.38, 70.75, 40.29], 1213: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0], 1214: [17, 25, 135, 1, 0.42, 0, 4, 23.37, 17.4, 4.93, 12.43, 8.27, 11.93, 65.77, 64.0, 42.25], 1215: [0, 25, 54, 0, 0.08, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0], 1216: [8, 25, 240, 0, 0.25, 0, 0, 22.61, 14.61, 4.61, 12.75, 6.71, 8.96, 59.46, 69.79, 45.92], 1217: [12, 25, 192, 0, 0.08, 0, 2, 23.56, 17.52, 6.15, 12.11, 8.15, 13.15, 67.15, 69.41, 48.78], 1218: [16, 25, 292, 0, 0.17, 0, 3, 25.79, 12.83, 6.14, 13.03, 6.72, 16.97, 68.62, 66.41, 47.11], 1219: [11, 25, 46, 0, 0.42, 0, 0, 26.0, 16.89, 6.25, 13.54, 8.61, 13.93, 73.14, 72.57, 42.02], 1220: [21, 25, 266, 0, 0.33, 0, 2, 25.72, 14.14, 7.41, 12.52, 7.86, 13.21, 72.86, 66.52, 47.53], 1221: [24, 25, 287, 0, 0.25, 0, 5, 23.77, 13.63, 6.33, 11.83, 10.4, 14.2, 66.73, 55.87, 46.08], 1222: [18, 25, 272, 0, 0.08, 0, 4, 24.29, 12.58, 8.58, 13.68, 10.55, 12.13, 69.58, 68.32, 44.57], 1223: [0, 25, 55, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40.42], 1224: [5, 25, 205, 0, 0.0, 0, 1, 21.96, 15.68, 7.32, 13.43, 6.96, 9.46, 64.0, 73.75, 43.53], 1225: [7, 25, 252, 0, 0.25, 0, 2, 22.79, 12.57, 5.32, 12.18, 5.5, 10.64, 60.64, 66.04, 51.45], 1226: [7, 25, 192, 0, 0.25, 0, 1, 21.32, 15.08, 5.12, 10.36, 8.0, 11.68, 63.2, 71.4, 44.49], 1227: [13, 25, 284, 0, 0.5, 0, 3, 25.31, 12.73, 5.15, 13.38, 6.77, 12.77, 69.35, 69.31, 49.61], 1228: [32, 1, 411, 20, 0.67, 0, 22, 28.15, 11.12, 8.7, 10.97, 7.64, 18.58, 77.42, 60.12, 58.73], 1229: [16, 25, 320, 2, 0.42, 0, 4, 23.66, 14.21, 6.38, 9.9, 6.45, 13.86, 66.24, 66.0, 52.54], 1230: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0], 1231: [15, 25, 412, 27, 0.5, 1, 23, 21.79, 12.89, 6.04, 10.32, 6.54, 11.93, 63.93, 63.5, 58.59], 1232: [11, 25, 204, 1, 0.17, 0, 3, 20.87, 12.97, 4.94, 9.32, 6.19, 11.9, 60.97, 64.81, 55.74], 1233: [15, 25, 321, 0, 0.33, 0, 7, 25.1, 15.29, 4.9, 11.9, 6.55, 14.65, 71.65, 71.32, 50.69], 1234: [21, 10, 368, 14, 0.5, 0, 14, 25.66, 14.53, 6.41, 11.09, 7.53, 15.5, 73.22, 67.03, 53.13], 1235: [18, 9, 329, 10, 0.5, 0, 14, 25.24, 12.93, 3.69, 11.76, 9.48, 14.24, 68.38, 64.14, 56.13], 1236: [6, 25, 11, 0, 0.0, 0, 0, 22.07, 16.07, 6.5, 11.04, 6.07, 11.75, 61.71, 71.14, 44.36], 1237: [14, 25, 74, 0, 0.33, 0, 1, 24.81, 10.93, 8.26, 12.37, 7.78, 14.0, 70.19, 68.59, 47.93], 1238: [14, 25, 243, 0, 0.17, 0, 3, 23.06, 17.55, 4.32, 14.16, 9.77, 11.84, 64.29, 69.16, 40.43], 1239: [14, 25, 234, 0, 0.17, 0, 1, 25.15, 18.04, 5.74, 10.85, 8.78, 13.85, 70.37, 74.85, 44.09], 1240: [4, 25, 99, 0, 0.25, 0, 0, 23.73, 15.58, 5.96, 10.27, 7.5, 12.54, 67.04, 74.96, 47.98], 1241: [6, 25, 292, 0, 0.0, 0, 2, 21.07, 17.25, 4.93, 11.64, 5.96, 10.61, 60.54, 72.21, 45.91], 1242: [23, 3, 473, 50, 0.67, 2, 28, 26.93, 14.48, 6.79, 11.79, 6.62, 16.59, 75.45, 65.24, 57.82], 1243: [15, 25, 284, 4, 0.25, 0, 11, 24.3, 12.33, 5.81, 11.52, 6.63, 15.52, 68.63, 66.37, 56.26], 1244: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 45.65], 1245: [18, 25, 298, 4, 0.5, 0, 5, 24.27, 13.43, 7.17, 11.77, 8.33, 14.73, 68.83, 65.8, 49.88], 1246: [25, 2, 466, 47, 0.83, 3, 24, 26.5, 13.03, 6.53, 12.7, 9.4, 15.27, 73.73, 61.9, 55.03], 1247: [10, 25, 296, 1, 0.08, 0, 5, 21.28, 13.59, 7.38, 9.03, 7.55, 12.62, 62.66, 68.21, 54.68], 1248: [8, 25, 245, 0, 0.08, 0, 2, 22.37, 17.67, 6.7, 10.15, 6.0, 12.04, 66.89, 75.63, 49.22], 1249: [14, 25, 248, 0, 0.08, 0, 2, 26.6, 15.44, 6.52, 13.68, 7.84, 13.92, 78.0, 75.8, 46.47], 1250: [13, 25, 202, 0, 0.33, 0, 5, 19.96, 13.57, 6.43, 10.5, 6.57, 12.79, 61.36, 61.32, 47.23], 1251: [12, 25, 170, 0, 0.33, 0, 3, 23.44, 15.85, 5.74, 13.04, 6.56, 12.19, 67.26, 74.07, 44.38], 1252: [14, 25, 11, 0, 0.0, 0, 0, 23.42, 15.92, 7.19, 12.38, 6.23, 12.42, 67.31, 68.92, 47.96], 1253: [10, 25, 258, 0, 0.0, 0, 4, 22.07, 16.13, 5.3, 11.87, 5.27, 11.2, 60.67, 66.33, 50.32], 1254: [13, 25, 190, 0, 0.08, 0, 4, 23.61, 15.86, 6.93, 11.61, 5.29, 12.75, 67.32, 71.71, 45.45], 1255: [1, 25, 0, 0, 0.0, 0, 0, 24.03, 17.03, 6.2, 12.27, 7.03, 12.8, 63.7, 80.57, 43.87], 1256: [14, 25, 318, 3, 0.33, 0, 4, 25.83, 15.03, 5.0, 13.38, 7.03, 15.55, 70.34, 70.52, 48.46], 1257: [27, 4, 387, 22, 0.33, 2, 22, 26.55, 14.39, 9.65, 12.71, 9.06, 15.94, 80.55, 62.65, 59.41], 1258: [11, 25, 225, 4, 0.5, 0, 3, 24.89, 13.68, 4.96, 12.11, 8.71, 15.39, 67.82, 70.57, 52.62], 1259: [6, 25, 185, 0, 0.0, 0, 2, 22.96, 17.61, 4.43, 12.36, 6.07, 11.96, 65.93, 75.54, 49.48], 1260: [12, 25, 223, 2, 0.33, 0, 1, 23.97, 15.41, 6.07, 9.97, 8.24, 12.03, 67.03, 69.72, 46.05], 1261: [20, 6, 329, 11, 0.25, 0, 14, 25.97, 13.24, 6.86, 11.48, 7.0, 14.9, 75.48, 71.03, 52.98], 1262: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0], 1263: [13, 25, 258, 0, 0.33, 0, 0, 22.32, 18.18, 6.79, 11.25, 7.43, 11.86, 62.64, 65.46, 46.72], 1264: [13, 25, 276, 2, 0.58, 0, 4, 25.89, 12.3, 5.22, 12.22, 8.22, 12.78, 72.44, 71.15, 50.12], 1265: [11, 25, 281, 0, 0.08, 0, 2, 24.21, 13.54, 8.25, 9.57, 5.86, 15.25, 70.04, 72.75, 48.76], 1266: [18, 25, 345, 7, 0.67, 0, 14, 22.59, 14.59, 7.93, 12.97, 4.1, 13.72, 67.72, 65.31, 58.15], 1267: [6, 25, 299, 0, 0.25, 0, 2, 22.54, 14.61, 7.36, 12.11, 5.43, 12.07, 66.75, 73.86, 52.02], 1268: [16, 25, 361, 26, 0.75, 1, 17, 29.0, 15.79, 5.64, 14.75, 8.32, 15.54, 82.32, 76.75, 53.76], 1269: [16, 25, 329, 11, 0.33, 0, 7, 23.04, 15.54, 5.64, 11.57, 8.32, 14.82, 64.36, 65.75, 54.9], 1270: [9, 25, 242, 0, 0.42, 0, 2, 25.83, 17.21, 5.75, 12.71, 8.67, 13.17, 73.0, 77.13, 46.29], 1271: [2, 25, 146, 0, 0.08, 0, 0, 19.46, 22.32, 5.25, 10.64, 5.46, 9.68, 56.46, 79.54, 45.58], 1272: [19, 25, 386, 12, 0.42, 0, 17, 23.44, 14.97, 6.85, 14.35, 7.15, 12.0, 70.65, 65.44, 54.77], 1273: [14, 25, 195, 0, 0.17, 0, 1, 28.42, 16.0, 8.31, 13.42, 9.23, 16.96, 79.96, 78.73, 46.18], 1274: [16, 25, 273, 3, 0.33, 0, 6, 26.36, 13.18, 6.57, 15.04, 7.32, 11.68, 71.57, 69.68, 59.56], 1275: [18, 25, 337, 3, 0.5, 0, 7, 23.14, 13.96, 7.0, 11.39, 5.29, 13.0, 65.46, 61.14, 49.76], 1276: [13, 25, 373, 26, 0.42, 1, 16, 22.26, 15.61, 5.0, 10.35, 5.58, 12.19, 61.65, 63.97, 55.94], 1277: [22, 5, 380, 26, 0.58, 1, 23, 27.71, 13.86, 6.86, 11.86, 7.71, 17.86, 78.07, 63.36, 59.66], 1278: [21, 8, 308, 10, 0.5, 0, 10, 24.19, 16.13, 5.32, 11.39, 9.13, 14.35, 68.45, 62.84, 59.58], 1279: [14, 25, 264, 3, 0.33, 0, 6, 23.84, 14.06, 6.77, 10.45, 7.74, 14.68, 63.84, 64.13, 52.35], 1280: [22, 9, 310, 8, 0.5, 0, 9, 25.56, 15.13, 5.81, 14.5, 6.94, 14.16, 72.44, 66.0, 52.53], 1281: [16, 25, 386, 12, 0.58, 0, 19, 21.75, 14.59, 6.47, 12.03, 6.31, 12.31, 64.19, 66.03, 55.92], 1282: [14, 25, 168, 0, 0.25, 0, 0, 25.46, 12.65, 7.31, 11.73, 7.12, 14.27, 72.5, 71.96, 49.6], 1283: [18, 25, 369, 3, 0.42, 0, 6, 24.3, 15.17, 5.17, 13.5, 7.9, 14.17, 72.1, 66.77, 54.43], 1284: [16, 25, 280, 0, 0.33, 0, 4, 21.28, 13.72, 6.59, 7.24, 7.9, 14.14, 63.62, 63.17, 47.06], 1285: [16, 16, 302, 0, 0.33, 0, 9, 23.43, 17.0, 5.82, 10.29, 5.89, 13.79, 69.29, 69.04, 46.85], 1286: [12, 25, 258, 0, 0.25, 0, 2, 24.23, 15.5, 7.5, 8.5, 6.88, 13.85, 66.81, 68.23, 41.78], 1287: [8, 25, 184, 0, 0.25, 0, 2, 22.17, 17.13, 3.92, 7.58, 5.04, 13.67, 62.08, 71.92, 52.07], 1288: [14, 25, 155, 0, 0.17, 0, 2, 24.23, 16.17, 5.17, 11.43, 7.87, 13.17, 65.4, 67.63, 41.5], 1289: [0, 25, 6, 0, 0.08, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0], 1290: [13, 25, 236, 0, 0.42, 0, 5, 24.64, 14.14, 7.07, 13.75, 9.39, 11.79, 66.96, 65.89, 41.88], 1291: [7, 25, 186, 0, 0.33, 0, 3, 23.22, 14.78, 7.33, 11.04, 6.19, 12.37, 65.37, 71.7, 48.8], 1292: [17, 25, 264, 1, 0.42, 0, 4, 24.28, 14.41, 6.17, 12.76, 6.0, 11.03, 70.21, 66.48, 51.59], 1293: [15, 25, 362, 1, 0.5, 0, 13, 26.08, 12.58, 7.15, 13.38, 7.38, 14.54, 70.81, 66.31, 48.6], 1294: [4, 25, 0, 0, 0.0, 0, 1, 22.88, 17.16, 6.12, 10.64, 6.32, 13.12, 63.36, 77.0, 45.79], 1295: [0, 25, 0, 0, 0.0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 48.65], 1296: [11, 25, 231, 0, 0.25, 0, 2, 24.0, 14.21, 7.07, 10.64, 5.79, 14.64, 68.43, 69.21, 45.95], 1297: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43.84], 1298: [8, 25, 271, 4, 0.25, 0, 6, 23.5, 18.96, 6.27, 15.92, 8.31, 11.88, 69.73, 74.96, 47.3], 1299: [6, 25, 243, 0, 0.08, 0, 7, 22.83, 20.27, 6.2, 12.13, 9.9, 11.33, 64.53, 73.97, 43.38], 1300: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 44.39], 1301: [19, 10, 332, 11, 0.42, 0, 13, 25.19, 12.28, 8.47, 11.09, 7.06, 15.31, 73.84, 66.38, 56.57], 1302: [0, 25, 62, 0, 0.17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0], 1303: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 45.63], 1304: [14, 25, 316, 0, 0.17, 0, 6, 23.61, 14.21, 6.21, 13.14, 5.82, 13.57, 68.04, 63.93, 58.24], 1305: [23, 9, 284, 2, 0.67, 0, 5, 24.72, 14.59, 2.69, 12.07, 6.69, 15.07, 69.55, 62.52, 55.72], 1306: [8, 25, 146, 0, 0.33, 0, 0, 23.15, 15.96, 5.44, 9.7, 6.96, 13.3, 63.96, 70.07, 46.83], 1307: [25, 12, 373, 4, 0.33, 0, 11, 25.97, 13.81, 8.29, 9.71, 7.52, 15.03, 75.87, 64.94, 60.32], 1308: [4, 25, 343, 3, 0.42, 0, 10, 23.71, 15.82, 6.71, 10.43, 4.82, 11.43, 66.32, 76.21, 52.46], 1309: [12, 25, 346, 1, 0.33, 0, 4, 24.21, 12.69, 5.0, 13.0, 6.07, 13.14, 66.55, 69.86, 41.29], 1310: [20, 14, 276, 0, 0.42, 0, 2, 27.9, 12.79, 9.1, 15.86, 6.86, 15.9, 85.17, 78.17, 49.86], 1311: [3, 25, 189, 0, 0.08, 0, 2, 23.38, 15.5, 7.71, 11.5, 6.71, 12.25, 70.71, 81.75, 45.08], 1312: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38.91], 1313: [13, 25, 80, 0, 0.33, 0, 1, 21.52, 17.19, 5.19, 12.67, 7.63, 11.04, 62.11, 61.67, 42.25], 1314: [27, 1, 456, 47, 0.5, 3, 26, 30.45, 16.68, 7.39, 13.77, 10.39, 19.32, 88.77, 70.26, 59.07], 1315: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 45.52], 1316: [0, 25, 0, 0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 47.48], 1317: [12, 25, 184, 0, 0.17, 0, 3, 24.92, 16.04, 6.0, 13.19, 7.31, 11.27, 71.88, 75.15, 48.63], 1318: [21, 25, 279, 0, 0.33, 0, 4, 26.33, 13.17, 7.8, 10.47, 7.

In [517]:
years = range(2003,2014)
x_train, y_train = trainingdata(years)
trainingdata=[x_train,y_train]
with open('/home/nishant/Desktop/train.p', 'wb') as outfile:  
    cp.dump(trainingdata, outfile)

In [516]:
import cPickle as cp
train=[x_train,y_train]
with open('/home/nishant/Desktop/x_train.p', 'wb') as outfile:  
    cp.dump(train, outfile)
with open('/home/nishant/Desktop/x_train.p', 'rb') as fp:  
    [xtrain1,ytrain1]=cp.load(fp)
#x_train==xtrain1
y_train==ytrain1

array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

In [505]:

x_train1=np.array(x_train1)

AttributeError: 'str' object has no attribute 'read'

In [417]:
dat=rsc[(rsc['season']==2008)]
oppl=list(dat[dat.wteam==1228].lteam.values)
oppw=list(dat[dat.lteam==1228].wteam.values)
oppall=oppl.append(oppw)
print len(oppl+oppw),len(oppl),len(oppw)

36 17 19

In [438]:
dat=rsc[(rsc['season']==2014)]
def owp(tid):
        lopp=list(dat[dat.wteam==tid].lteam.values)
        wopp=list(dat[dat.lteam==tid].wteam.values)
        allopp=lopp+wopp
        #print allopp
        wp=[]
        for i in allopp:
            print i
            won=len(dat[(dat.wteam==i)&(dat.lteam!=tid)].index)
            print won
            lost=len(dat[(dat.lteam==i)&(dat.wteam!=tid)].index)
            print lost
            wp.append(float(won)/(won+lost)*100)
        print wp
        return sum(wp)/float(len(wp))
op=owp(1113)
#print op

1420
8
20
1275
13
16
1226
9
17
1424
20
12
1133
12
19
1266
17
14
1158
13
17
1177
12
20
1212
4
22
1403
14
17
1414
21
10
1450
9
20
1425
10
20
1428
18
10
1160
22
10
1143
19
11
1333
15
14
1332
22
8
1112
29
3
1390
19
11
1143
19
11
1166
25
7
1274
16
16
1449
16
15
1417
25
8
1112
29
3
1390
19
11
1160
22
10
1428
18
10
1332
22
8
1333
15
14
1390
19
11
[28.57142857142857, 44.827586206896555, 34.61538461538461, 62.5, 38.70967741935484, 54.83870967741935, 43.333333333333336, 37.5, 15.384615384615385, 45.16129032258064, 67.74193548387096, 31.03448275862069, 33.33333333333333, 64.28571428571429, 68.75, 63.33333333333333, 51.724137931034484, 73.33333333333333, 90.625, 63.33333333333333, 63.33333333333333, 78.125, 50.0, 51.61290322580645, 75.75757575757575, 90.625, 63.33333333333333, 68.75, 64.28571428571429, 73.33333333333333, 51.724137931034484, 63.33333333333333]